/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProctorRouteImport } from './routes/proctor'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWellKnownAssetlinksRouteImport } from './routes/api/public/well-known/assetlinks'

const ProctorRoute = ProctorRouteImport.update({
  id: '/proctor',
  path: '/proctor',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWellKnownAssetlinksRoute =
  ApiPublicWellKnownAssetlinksRouteImport.update({
    id: '/api/public/well-known/assetlinks',
    path: '/api/public/well-known/assetlinks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRoute
  '/proctor': typeof ProctorRoute
  '/api/public/well-known/assetlinks': typeof ApiPublicWellKnownAssetlinksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner': typeof OwnerRoute
  '/proctor': typeof ProctorRoute
  '/api/public/well-known/assetlinks': typeof ApiPublicWellKnownAssetlinksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner': typeof OwnerRoute
  '/proctor': typeof ProctorRoute
  '/api/public/well-known/assetlinks': typeof ApiPublicWellKnownAssetlinksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/owner' | '/proctor' | '/api/public/well-known/assetlinks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/owner' | '/proctor' | '/api/public/well-known/assetlinks'
  id:
    | '__root__'
    | '/'
    | '/owner'
    | '/proctor'
    | '/api/public/well-known/assetlinks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRoute
  ProctorRoute: typeof ProctorRoute
  ApiPublicWellKnownAssetlinksRoute: typeof ApiPublicWellKnownAssetlinksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proctor': {
      id: '/proctor'
      path: '/proctor'
      fullPath: '/proctor'
      preLoaderRoute: typeof ProctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/well-known/assetlinks': {
      id: '/api/public/well-known/assetlinks'
      path: '/api/public/well-known/assetlinks'
      fullPath: '/api/public/well-known/assetlinks'
      preLoaderRoute: typeof ApiPublicWellKnownAssetlinksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRoute,
  ProctorRoute: ProctorRoute,
  ApiPublicWellKnownAssetlinksRoute: ApiPublicWellKnownAssetlinksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
